"""add_contact_linkedin_fields

Revision ID: 7a6c1a445709
Revises: 
Create Date: 2026-04-24 17:27:09.938801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6c1a445709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('headline', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'location')
    op.drop_column('contacts', 'headline')
    op.drop_column('contacts', 'job_title')
    # ### end Alembic commands ###
